version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for NuGet (Backend)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "Microsoft.AspNetCore.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.EntityFrameworkCore.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Serilog.AspNetCore"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Swashbuckle.AspNetCore"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for npm (Frontend)
  - package-ecosystem: "npm"
    directory: "/DocumentGenerator.Client"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
