version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for NuGet (Backend)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Maintain dependencies for npm (Frontend)
  - package-ecosystem: "npm"
    directory: "/DocumentGenerator.Client"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
